In [7]:
import numpy as np

In [8]:
a=np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [14]:
print(a)

[1 2 3]


In [16]:
type(a)

numpy.ndarray

In [18]:
a.shape

(3,)

In [100]:
b=np.array([[1,2,3],[4,5,6]])

In [101]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
b.shape

(2, 3)

In [103]:
c1=np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [104]:
c2=c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
c3=c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [106]:
c4=c2.flatten() #copyを返す
c4

array([0, 1, 2, 3, 4, 5])

In [107]:
a.dtype

dtype('int32')

In [108]:
d=np.array([1,2],dtype=np.int16)
d

array([1, 2], dtype=int16)

In [109]:
d.dtype

dtype('int16')

In [110]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [111]:
a

array([1, 2, 4])

In [112]:
a[0]

1

In [113]:
a[1:]

array([2, 4])

In [114]:
a[-1]

4

In [115]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
b[0]

array([1, 2, 3])

In [117]:
b[1,0]

4

In [118]:
b[:,2]

array([3, 6])

In [119]:
b[1,:]

array([4, 5, 6])

In [120]:
b[0,1:]

array([2, 3])

In [121]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [122]:
a

array([1, 2, 4])

In [123]:
a[2]=4
a

array([1, 2, 4])

In [124]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
b[1,2]=7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [126]:
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [127]:
a1=a
a1

array([1, 2, 4])

In [128]:
a1[1]=5
a1

array([1, 5, 4])

In [129]:
a

array([1, 5, 4])

In [130]:
a2=a.copy()
a2

array([1, 5, 4])

In [131]:
a2[0]=6
a2

array([6, 5, 4])

In [132]:
a

array([1, 5, 4])

In [133]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [134]:
c3=c2.ravel()
c4=c2.flatten()
c3[0]=6
c4[1]=7

In [135]:
c3

array([6, 1, 2, 3, 4, 5])

In [136]:
c4

array([0, 7, 2, 3, 4, 5])

In [137]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [138]:
c4[0]

0

In [139]:
py_list1=[0,1]
py_list2=py_list1[:]
py_list2[0]=2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [140]:
np_array1=np.array([0,1])
np_array2=np_array1[:]
np_array2[0]=2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [141]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [144]:
f=np.random.random((3,2))
f

array([[0.95813109, 0.37872547],
       [0.692066  , 0.74260018],
       [0.11838515, 0.15496926]])

In [145]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [146]:
np.random.seed(123)
np.random.rand(4,2)

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [147]:
np.random.seed(123)
np.random.randint(1,10)

3

In [148]:
np.random.seed(123)
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [149]:
np.random.seed(123)
np.random.uniform(0.0,5.0,size=(2,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [150]:
np.random.seed(123)
np.random.uniform(size=(4,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [151]:
np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [152]:
np.zeros(3)

array([0., 0., 0.])

In [153]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [154]:
np.ones(2)

array([1., 1.])

In [155]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [156]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [157]:
np.full(3,3.14)

array([3.14, 3.14, 3.14])

In [158]:
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [159]:
np.nan

nan

In [160]:
np.array([1,2,np.nan])

array([ 1.,  2., nan])

In [161]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [162]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [163]:
l=np.array([2,2,6,1,4])
np.diff(l)

array([ 0,  4, -5,  3])

In [164]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [165]:
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [166]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [169]:
b1=np.array([[10],[20]])
b1

array([[10],
       [20]])

In [170]:
np.concatenate([b,b1],axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [171]:
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [172]:
b2=np.array([30,60,45])
b2

array([30, 60, 45])

b3=np.vstack([b,b2])
b3

In [173]:
b3=np.vstack([b,b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [174]:
first,second=np.hsplit(b3,[2])

### 

In [175]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [176]:
second

array([[ 8],
       [ 8],
       [45]])

In [177]:
first1,second1=np.vsplit(b3,[2])

In [178]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [180]:
second1

array([[30, 60, 45]])

In [181]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [182]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [183]:
a

array([1, 5, 4])

In [184]:
a[np.newaxis,:]

array([[1, 5, 4]])

In [185]:
a[:,np.newaxis]

array([[1],
       [5],
       [4]])

In [186]:
m=np.arange(0,4)
m

array([0, 1, 2, 3])

In [187]:
n=np.arange(4,7)
n

array([4, 5, 6])

In [189]:
xx,yy=np.meshgrid(m,n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [190]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])